#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# License: GNU General Public License v2
#
#
# Author: thl-cmk[at]outlook[dot]com
# URL   : https://thl-cmk.hopto.org
# Date  : 2024-04-29
# File  : checks/agent_freeradius
#
#

from collections.abc import Mapping, Sequence
from typing import Any


def agent_freeradius_arguments(
        params: Mapping[str, Any],
        hostname: str,
        ipaddress: str | None,
) -> Sequence[object]:
    args = []

    if ipaddress is not None:
        args.extend(['-H', ipaddress])
    else:
        args.append('-H $HOSTADDRESS$')

    if (auth_port := params.get("auth_port")) is not None:
        args.extend(['--auth-port', auth_port])

    if (secret := params.get("secret")) is not None:
        args.extend(["--secret", passwordstore_get_cmdline("%s", secret)])

    if (timeout := params.get('timeout')) is not None:
        args.extend(['--timeout', timeout])

    # if (user_name := params.get("user_name")) is not None:
    #     args.extend([f'--username', user_name])
    #
    # if (user_password := params.get("user_password")) is not None:
    #     args.extend(["--password", passwordstore_get_cmdline("%s", user_password)])

    return args


special_agent_info["freeradius"] = agent_freeradius_arguments
